apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      tag: "v1.16.6"
    kubeProxyReplacement: true
    k8sServiceHost: {{ rke2_api_ip }}
    k8sServicePort: {{ rke2_apiserver_dest_port }}
    cni:
      chainingMode: "none"
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
        image:
          tag: "v1.16.6"
