# TODO: setup lvm with disks and mount to /data. Create PVCs that mount /data

# This should automate 90% of the work, maybe the rest might stay manual

- name: Setup vLLM and dependencies
  # hosts: testing
  hosts: "{{ target_host }}"
  gather_facts: true
  # serial: 1
  become: true
  # vars_files:
  #   - vars/disks.yml
  tasks:
  # Gather some additional facts
  - name: Get nvidia_keyring fact
    ansible.builtin.stat:
      path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    register: nvidia_keyring
  - name: Get nvidia repo list
    ansible.builtin.stat:
      path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    register: nvidia_repo_list
  - name: Populate service facts
    ansible.builtin.service_facts:

  # - name: Extend volume group with available physical volumes
  #   community.general.lvg:
  #     vg: "{{ vg }}"
  #     pvs: "{{ disks[ansible_host] }}"
  
  # - name: Extend the logical volume to fill the entire volume group
  #   community.general.lvol:
  #     vg: "{{ vg }}"
  #     lv: "{{ lv }}"
  #     size: 100%FREE

  - name: Remove unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: absent

  - name: Install pip and nmcli
    ansible.builtin.apt:
      update_cache: yes
      pkg:
        - python3-pip
        # for creating dummy network
        - network-manager

  - name: Install pip dependencies for k8s ansible module
    ansible.builtin.pip:
      break_system_packages: true
      name:
        - kubernetes
        - pyyaml
        - jsonpatch

  # This one worked
  # - name: Create dummy loopback interface so k3s is not confused when switching ethernet cards
  #   ansible.builtin.shell: nmcli connection add type dummy ifname dummy0 ipv4.addresses 172.31.255.1/32 ipv4.method manual autoconnect yes

  - name: Enable rule to manage dummy network interface
    ansible.builtin.copy:
      dest: "/etc/NetworkManager/conf.d/90-manage-dummy0.conf"
      content: |
        [keyfile]
        unmanaged-devices=interface-name:!*dummy0
    register: nmcli_dummy0_managed

  - name: Restart NetworkManager
    when: nmcli_dummy0_managed.changed
    ansible.builtin.systemd:
      state: restarted
      name: NetworkManager

  - name: Create dummy loopback interface so k3s is not confused when switching ethernet cards
    community.general.nmcli:
      conn_name: dummy0
      ifname: dummy0
      type: dummy
      ip4: 172.31.255.1/32
      method4: manual
      state: present
      autoconnect: true

  # - name: Check dummy network
  #   ansible.builtin.pause:
  #     prompt: "Check dummy network"

  # TODO: add label '"nvidia.com/gpu.present: "true"' to node, so nvidia device plugin daemonset gets scheduled there

  - name: Fetch nvidia repo gpg key
    when: not nvidia_keyring.stat.exists
    ansible.builtin.shell: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

  - name: Add nvidia repo
    when: not nvidia_repo_list.stat.exists
    ansible.builtin.shell: >-
      curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' > /etc/apt/sources.list.d/nvidia-container-toolkit.list

  # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#next-steps
  - name: Install nvidia container runtime (toolkit)
    vars:
      nvidia_toolkit_version: 1.17.8-1
    ansible.builtin.apt:
      update_cache: yes
      pkg:
        - nvidia-container-toolkit={{nvidia_toolkit_version }}
        - nvidia-container-toolkit-base={{nvidia_toolkit_version }}
        - libnvidia-container-tools={{nvidia_toolkit_version }}
        - libnvidia-container1={{nvidia_toolkit_version }}

  - name: Install k3s compatible drivers
    vars:
      nvidia_driver_version: 580
    ansible.builtin.apt:
      update_cache: yes
      pkg:
        - nvidia-container-runtime
        - cuda-drivers-fabricmanager-{{ nvidia_driver_version }}
        - nvidia-headless-{{ nvidia_driver_version }}-server-open
        - nvidia-utils-{{ nvidia_driver_version }}-server

  # - name: Check nvidia drivers
  #   ansible.builtin.pause:
  #     prompt: "Check nvidia drivers"

  - name: Install k3s
    when: ansible_facts.services['k3s.service']['status'] | default('not-found') == 'not-found'
    # TODO: disable traefik at startup
    ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --default-runtime=nvidia --advertise-address 172.31.255.1" sh -
    # ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --default-runtime=nvidia" sh -

  - name: Ensure system-reserved and kube-reserved for newer k3s versions
    ansible.builtin.copy:
      dest: /var/lib/rancher/k3s/agent/etc/kubelet.conf.d/90-k3s-reservations.conf
      content: |
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        systemReserved:
          cpu: "6"
          memory: "26Gi"
        kubeReserved:
          cpu: "1"
          memory: "2Gi"
    register: k3s_reservations

  - name: Restart k3s service
    when: k3s_reservations.changed
    ansible.builtin.systemd:
      state: restarted
      name: k3s

  # - name: Check k3s
  #   ansible.builtin.pause:
  #     prompt: "Check k3s"

  - name: Install helm
    ansible.builtin.shell: >-
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
      && chmod 700 get_helm.sh \
      && ./get_helm.sh

  - name: Copy kubeconfig file so helm can see it (embedded kubectl looks at /etc/rancher/k3s/k3s.yaml)
    ansible.builtin.copy:
      remote_src: true
      src: /etc/rancher/k3s/k3s.yaml
      dest: /root/.kube/config

  - name: Enable nvidia helm repository
    kubernetes.core.helm_repository:
      name: nvdp
      repo_url: https://nvidia.github.io/k8s-device-plugin
  
  # - name: Install k8s-device-plugin helmchart
  #   ansible.builtin.shell: >-
  #     helm upgrade -i nvdp nvdp/nvidia-device-plugin \
  #       --namespace nvidia-device-plugin \
  #       --create-namespace \
  #       --version 0.17.1
  #   changed_when: does not exist

  - name: Install k8s-device-plugin helmchart
    kubernetes.core.helm:
      name: nvdp
      chart_ref: nvdp/nvidia-device-plugin
      chart_version: 0.17.1
      create_namespace: true
      release_namespace: nvidia-device-plugin

  - name: Create vllm namespace
    kubernetes.core.k8s:
      name: vllm
      api_version: v1
      kind: Namespace
      state: present

  - name: Copy deployments files
    ansible.builtin.copy:
      # remote_src: true
      src: deployments/{{ item }}-deployment.yml
      dest: /root/{{ item }}-deployment.yml
    loop:
      - qwen
      - phi
    register: deployment_file

  - ansible.builtin.debug:
      msg: "{{ deployment_file }}"

  - name: Apply k8s deployments
    kubernetes.core.k8s:
      state: present
      src: /root/{{ item }}-deployment.yml
    loop:
      - qwen
      - phi

  # In case you mess things up with the operator, refer to this: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/uninstall.html