---
# roles:
#   # Install a role from Ansible Galaxy.
#   - name: geerlingguy.mysql
#     version: 4.3.3

collections:
  # Install a collection from Ansible Galaxy.
  - name: kubernetes.core
  - name: community.general
    # version: 1.4.0
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: <comit-ish>
